export const colors = {
  primary: '#6B1D2E',
  primaryDark: '#4B1824',
  primaryDeep: '#1A0A10',
  secondary: '#C9961A',
  accent: '#3A9BBF',
  background: '#FAF8F5',
  surface: '#FFFFFF',
  surfaceMuted: '#F2EDE8',
  textPrimary: '#1A0A10',
  textSecondary: '#6B6B6B',
  border: '#F2EDE8',
  success: '#2F7D4A',
  warning: '#C9961A',
  error: '#B42318',
  infoSurface: '#E8F6FB',
  goldSurface: '#FBF4E3',
  lilacSurface: '#F0EBF5',
  greenSurface: '#EBF5EB',
  roseSurface: '#FBF0EE',
  white: '#FFFFFF',
  transparent: 'transparent',
} as const;

